version: "3.8"

services:
  pentaho-carte:
    image: quarrierzhang/pentaho-carte:9.0
    environment:
      SERVER_PORT: 8081
      SERVER_HOST: '0.0.0.0'
      SERVER_NAME: 'ifca-Master'
      SERVER_USER: 'admin'
      SERVER_PASSWD: '123456'
      RUNMODE: 'master'
    volumes:
      - "pentaho-carte:/data-integration"
    ports:
      - "8081:8081"
      - "8802:8802"
      - "9051:9051"
    restart: always
    container_name: pentaho-carte
    privileged: true
    # hostname: 'localhost'
    # ipc: host
    # network_mode: "host"
    # networks:
        # carte-net: {}
    # networks:
      # hostnet: {}
  
volumes:
  pentaho-carte:
    name: pentaho-carte
# networks:
  # carte-net:
    # name: carte-net
    # drive: host
# networks:
  # hostnet:
    # external:
      # name: host